apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanver-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanver-app
  template:
    metadata:
      labels:
        app: kanver-app
    spec:
      containers:
        - name: kanver-app
          image: kanveracr.azurecr.io/kanver-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/kanver
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
